# Generated by Django 5.2.4 on 2025-08-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="URL for user's profile picture from social login", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', help_text='Last login method used', max_length=20),
        ),
    ]
