# Generated by Django 4.2.9 on 2025-07-13 10:55

import apps.transcripts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the transcript', max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(help_text='Transcript text file', upload_to=apps.transcripts.models.transcript_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('content', models.TextField(help_text='Text content of the transcript')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('character_count', models.PositiveIntegerField(default=0, help_text='Number of characters in the content')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Estimated number of words in the content')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this transcript has been processed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transcript Document',
                'verbose_name_plural': 'Transcript Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
