# Generated by Django 4.2.9 on 2025-07-13 10:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_mode', models.CharField(choices=[('proofreading', 'Proofreading (Typo Correction)'), ('grammar', 'Grammar Correction'), ('summary', 'Summary Generation'), ('custom', 'Custom Processing')], default='proofreading', max_length=20)),
                ('custom_prompt', models.TextField(blank=True, help_text='Custom instructions for processing')),
                ('model_used', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-4o', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('corrected_content', models.TextField(blank=True, help_text='Corrected text output')),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='API cost for this job in USD', max_digits=10)),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Number of input tokens used')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Number of output tokens generated')),
                ('processing_time', models.DurationField(blank=True, help_text='Time taken to process', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_jobs', to='transcripts.transcriptdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_jobs', to=settings.AUTH_USER_MODEL)),
                ('wordlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_jobs', to='wordlists.wordlist')),
            ],
            options={
                'verbose_name': 'Correction Job',
                'verbose_name_plural': 'Correction Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionJobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='corrections.correctionjob')),
            ],
            options={
                'verbose_name': 'Correction Job History',
                'verbose_name_plural': 'Correction Job Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
