# Generated by Django 4.2.9 on 2025-07-13 10:55

import apps.wordlists.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the word list', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the word list')),
                ('csv_file', models.FileField(blank=True, help_text='CSV file containing word corrections', null=True, upload_to=apps.wordlists.models.wordlist_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('csv_content', models.TextField(help_text='CSV content as text')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Number of word pairs in the list')),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this word list is shared with other users')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this word list is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word List',
                'verbose_name_plural': 'Word Lists',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SharedWordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False, help_text='Whether the user can edit this shared word list')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_wordlists', to=settings.AUTH_USER_MODEL)),
                ('wordlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_access', to='wordlists.wordlist')),
            ],
            options={
                'verbose_name': 'Shared Word List',
                'verbose_name_plural': 'Shared Word Lists',
                'unique_together': {('wordlist', 'user')},
            },
        ),
    ]
